#!/usr/bin/env bash
set -e
cd "$(git rev-parse --show-toplevel)"

# Create doc directory if it doesn't exist
mkdir -p doc

# =============================================================================
# 1. Generate API docs with lemmy-help (to temp file)
# =============================================================================

# Detect OS and download lemmy-help
case "$(uname)" in
  Darwin) RELEASE="x86_64-apple-darwin" ;;
  Linux)  RELEASE="x86_64-unknown-linux-gnu" ;;
  *)      echo "Unsupported OS: $(uname)"; exit 1 ;;
esac

LEMMY_VERSION="v0.11.0"
echo "Downloading lemmy-help ${LEMMY_VERSION} for ${RELEASE}..."
curl -sL "https://github.com/numToStr/lemmy-help/releases/download/${LEMMY_VERSION}/lemmy-help-${RELEASE}.tar.gz" | tar xz

API_DOCS=$(mktemp)
echo "Generating API documentation..."
./lemmy-help -f -a -c -t \
  lua/yaml-companion/init.lua \
  lua/yaml-companion/meta.lua \
  > "$API_DOCS"

rm -f lemmy-help

# =============================================================================
# 2. Generate vimdoc from README with panvimdoc
# =============================================================================

if ! command -v pandoc &> /dev/null; then
  echo "Warning: pandoc not found, skipping README vimdoc generation"
  echo "Install pandoc to generate doc/yaml-companion.txt locally"
  rm -f "$API_DOCS"
  exit 0
fi

echo "Generating vimdoc from README..."

# Clone panvimdoc to temp directory
PANVIMDOC_DIR=$(mktemp -d)
trap "rm -rf $PANVIMDOC_DIR $API_DOCS" EXIT
git clone --depth 1 --quiet https://github.com/kdheepak/panvimdoc.git "$PANVIMDOC_DIR"

# Create a temporary README with:
# - Emojis stripped (they render poorly in vimdoc)
# - Badges and images removed (not useful in vimdoc)
# - Main heading simplified to avoid duplicate "yaml-companion-yaml-companion" tags
# - Table of Contents section removed (panvimdoc generates its own)
# - Lua API section removed (we generate it from source annotations)
README_CLEAN=$(mktemp).md
perl -CSD -0777 -pe '
  s/[\x{1F300}-\x{1FAF8}\x{2600}-\x{26FF}\x{2700}-\x{27BF}\x{2328}\x{23CF}\x{23E9}-\x{23F3}\x{23F8}-\x{23FA}]\x{FE0F}?//g;
  s/^\[!\[.*?\]\(.*?\)\]\(.*?\)\n//gm;
  s/^!\[.*?\]\(.*?\)\n//gm;
  s/^# yaml-companion\.nvim$/# Introduction/m;
  s/^## Table of Contents\n(?:.*\n)*?(?=^## |\z)//m;
  s/^## Lua API\n(?:.*\n)*?(?=^## |\z)//m;
' README.md > "$README_CLEAN"

# Run panvimdoc
pandoc \
  --metadata=project:yaml-companion \
  --metadata=description:"YAML schema companion for Neovim" \
  --metadata=toc:true \
  --metadata=treesitter:true \
  --metadata=vimversion:"Neovim >= 0.11.0" \
  --metadata=incrementheadinglevelby:0 \
  --metadata=dedupsubheadings:true \
  --metadata=ignorerawblocks:true \
  --metadata=docmapping:false \
  --metadata=docmappingproject:true \
  --lua-filter="$PANVIMDOC_DIR/scripts/skip-blocks.lua" \
  --lua-filter="$PANVIMDOC_DIR/scripts/include-files.lua" \
  -t "$PANVIMDOC_DIR/scripts/panvimdoc.lua" \
  "$README_CLEAN" \
  -o doc/yaml-companion.txt

rm -f "$README_CLEAN"

# =============================================================================
# 3. Insert API docs before the panvimdoc footer
# =============================================================================

echo "Inserting API reference..."

# Create API section with header
API_SECTION=$(mktemp)
cat > "$API_SECTION" << 'EOF'
==============================================================================
API Reference                                        *yaml-companion-api*

Generated from Lua source annotations using lemmy-help.

EOF
# Append API docs, stripping the vim modeline that lemmy-help adds
grep -v '^vim:tw=78' "$API_DOCS" >> "$API_SECTION"

# Insert API section before the panvimdoc footer (the "Generated by panvimdoc" line)
perl -i -0777 -pe '
  open(my $fh, "<", "'"$API_SECTION"'") or die;
  local $/; my $api = <$fh>; close($fh);
  s/(Generated by panvimdoc)/$api\n$1/;
' doc/yaml-companion.txt

rm -f "$API_SECTION"

# =============================================================================
# 4. Post-process the combined vimdoc
# =============================================================================

# - Simplify tag names by removing redundant "-introduction" from tags
# - Flatten TOC numbering (convert nested "  - Item" to numbered list)
# - Replace M. prefix with yaml_companion. in API docs
perl scripts/fix-vimdoc-toc.pl doc/yaml-companion.txt

echo "Generated doc/yaml-companion.txt"
